//<auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//</auto-generated>

using UnityEngine.UIElements;

namespace UxmlBindings
{
	public partial struct AnimeLobbyViewBinding
	{
		private VisualElement _____root_____; // avoid name collisions!
		public VisualElement GetRootElement() => _____root_____;

		public readonly VisualElement Root_Container;
		public readonly Label Label_PlayerLevel;
		public readonly Button Button_Privilege;
		public readonly Button Button_Archive;
		public readonly Label Label_Energy;
		public readonly Label Label_Coin;
		public readonly Label Label_Maigo;
		public readonly Button Button_Activity;
		public readonly Button Button_Shop;
		public readonly Button Button_Gacha;
		public readonly Button Button_Social;
		public readonly Button Button_Roster;
		public readonly Button Button_Inventory;

		public AnimeLobbyViewBinding(VisualElement parent)
		{
			_____root_____ = parent;
			Root_Container = parent.Q<VisualElement>("Root_Container");
			Label_PlayerLevel = parent.Q<Label>("Label_PlayerLevel");
			Button_Privilege = parent.Q<Button>("Button_Privilege");
			Button_Archive = parent.Q<Button>("Button_Archive");
			Label_Energy = parent.Q<Label>("Label_Energy");
			Label_Coin = parent.Q<Label>("Label_Coin");
			Label_Maigo = parent.Q<Label>("Label_Maigo");
			Button_Activity = parent.Q<Button>("Button_Activity");
			Button_Shop = parent.Q<Button>("Button_Shop");
			Button_Gacha = parent.Q<Button>("Button_Gacha");
			Button_Social = parent.Q<Button>("Button_Social");
			Button_Roster = parent.Q<Button>("Button_Roster");
			Button_Inventory = parent.Q<Button>("Button_Inventory");
		}
	}
}
