//<auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//</auto-generated>

using UnityEngine.UIElements;

namespace UxmlBindings
{
	public partial struct StreamExperienceViewBinding
	{
		private VisualElement _____root_____; // avoid name collisions!
		public VisualElement GetRootElement() => _____root_____;

		public readonly VisualElement Root_Container;
		public readonly VisualElement Orb_Blue;
		public readonly VisualElement Orb_Purple;
		public readonly VisualElement Layer_Particles;
		public readonly VisualElement Live_Ping;
		public readonly VisualElement Nav_Scenes;
		public readonly Button Tab_Starting;
		public readonly Button Tab_Break;
		public readonly Button Tab_Ending;
		public readonly Button Tab_Ingame;
		public readonly Button Tab_Alerts;
		public readonly Button Button_Sound;
		public readonly Button Button_TestAlert;
		public readonly Button Button_Fullscreen;
		public readonly VisualElement Screen_Frame;
		public readonly VisualElement Scene_Hero;
		public readonly VisualElement Phone_Card;
		public readonly Label Label_Clock;
		public readonly ScrollView Scroll_Chat;
		public readonly TextField TextField_ChatInput;
		public readonly Button Button_Send;
		public readonly Button Button_Love;
		public readonly Button Button_Comment;
		public readonly Button Button_Share;
		public readonly Button Button_Bookmark;
		public readonly VisualElement Typing_Tooltip;
		public readonly VisualElement Hero_Right;
		public readonly VisualElement Hero_Diamond;
		public readonly VisualElement Hero_Capsule;
		public readonly VisualElement Capsule_Ping;
		public readonly Label Label_Capsule;
		public readonly Label Label_HeroTitle;
		public readonly Label Float_Heart;
		public readonly VisualElement Float_Diamond;
		public readonly Label Float_Plus;
		public readonly Label Label_HeroSubtitle;
		public readonly Label Label_Countdown;
		public readonly Label Label_StreamingText;
		public readonly VisualElement Scene_Ingame;
		public readonly Label Label_RecBadge;
		public readonly ScrollView Scroll_MiniChat;
		public readonly VisualElement Scene_Alerts;
		public readonly VisualElement Alerts_Grid;
		public readonly Button Dock_Starting;
		public readonly Button Dock_Break;
		public readonly Button Dock_Ending;
		public readonly Button Dock_Ingame;
		public readonly Button Dock_Alerts;
		public readonly Button Button_Heart;
		public readonly VisualElement Alert_Popup;
		public readonly Label Label_AlertIcon;
		public readonly Label Label_AlertTag;
		public readonly Label Label_AlertUser;
		public readonly Label Label_AlertMsg;
		public readonly Button Button_AlertClose;
		public readonly VisualElement Toast_Box;
		public readonly Label Label_Toast;

		public StreamExperienceViewBinding(VisualElement parent)
		{
			_____root_____ = parent;
			Root_Container = parent.Q<VisualElement>("Root_Container");
			Orb_Blue = parent.Q<VisualElement>("Orb_Blue");
			Orb_Purple = parent.Q<VisualElement>("Orb_Purple");
			Layer_Particles = parent.Q<VisualElement>("Layer_Particles");
			Live_Ping = parent.Q<VisualElement>("Live_Ping");
			Nav_Scenes = parent.Q<VisualElement>("Nav_Scenes");
			Tab_Starting = parent.Q<Button>("Tab_Starting");
			Tab_Break = parent.Q<Button>("Tab_Break");
			Tab_Ending = parent.Q<Button>("Tab_Ending");
			Tab_Ingame = parent.Q<Button>("Tab_Ingame");
			Tab_Alerts = parent.Q<Button>("Tab_Alerts");
			Button_Sound = parent.Q<Button>("Button_Sound");
			Button_TestAlert = parent.Q<Button>("Button_TestAlert");
			Button_Fullscreen = parent.Q<Button>("Button_Fullscreen");
			Screen_Frame = parent.Q<VisualElement>("Screen_Frame");
			Scene_Hero = parent.Q<VisualElement>("Scene_Hero");
			Phone_Card = parent.Q<VisualElement>("Phone_Card");
			Label_Clock = parent.Q<Label>("Label_Clock");
			Scroll_Chat = parent.Q<ScrollView>("Scroll_Chat");
			TextField_ChatInput = parent.Q<TextField>("TextField_ChatInput");
			Button_Send = parent.Q<Button>("Button_Send");
			Button_Love = parent.Q<Button>("Button_Love");
			Button_Comment = parent.Q<Button>("Button_Comment");
			Button_Share = parent.Q<Button>("Button_Share");
			Button_Bookmark = parent.Q<Button>("Button_Bookmark");
			Typing_Tooltip = parent.Q<VisualElement>("Typing_Tooltip");
			Hero_Right = parent.Q<VisualElement>("Hero_Right");
			Hero_Diamond = parent.Q<VisualElement>("Hero_Diamond");
			Hero_Capsule = parent.Q<VisualElement>("Hero_Capsule");
			Capsule_Ping = parent.Q<VisualElement>("Capsule_Ping");
			Label_Capsule = parent.Q<Label>("Label_Capsule");
			Label_HeroTitle = parent.Q<Label>("Label_HeroTitle");
			Float_Heart = parent.Q<Label>("Float_Heart");
			Float_Diamond = parent.Q<VisualElement>("Float_Diamond");
			Float_Plus = parent.Q<Label>("Float_Plus");
			Label_HeroSubtitle = parent.Q<Label>("Label_HeroSubtitle");
			Label_Countdown = parent.Q<Label>("Label_Countdown");
			Label_StreamingText = parent.Q<Label>("Label_StreamingText");
			Scene_Ingame = parent.Q<VisualElement>("Scene_Ingame");
			Label_RecBadge = parent.Q<Label>("Label_RecBadge");
			Scroll_MiniChat = parent.Q<ScrollView>("Scroll_MiniChat");
			Scene_Alerts = parent.Q<VisualElement>("Scene_Alerts");
			Alerts_Grid = parent.Q<VisualElement>("Alerts_Grid");
			Dock_Starting = parent.Q<Button>("Dock_Starting");
			Dock_Break = parent.Q<Button>("Dock_Break");
			Dock_Ending = parent.Q<Button>("Dock_Ending");
			Dock_Ingame = parent.Q<Button>("Dock_Ingame");
			Dock_Alerts = parent.Q<Button>("Dock_Alerts");
			Button_Heart = parent.Q<Button>("Button_Heart");
			Alert_Popup = parent.Q<VisualElement>("Alert_Popup");
			Label_AlertIcon = parent.Q<Label>("Label_AlertIcon");
			Label_AlertTag = parent.Q<Label>("Label_AlertTag");
			Label_AlertUser = parent.Q<Label>("Label_AlertUser");
			Label_AlertMsg = parent.Q<Label>("Label_AlertMsg");
			Button_AlertClose = parent.Q<Button>("Button_AlertClose");
			Toast_Box = parent.Q<VisualElement>("Toast_Box");
			Label_Toast = parent.Q<Label>("Label_Toast");
		}
	}
}
