//<auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//</auto-generated>

using UnityEngine.UIElements;

namespace UxmlBindings
{
	public partial struct VisualNovelViewBinding
	{
		private VisualElement _____root_____; // avoid name collisions!
		public VisualElement GetRootElement() => _____root_____;

		public readonly VisualElement VisualElement_VignetteFlash;
		public readonly Button Button_Auto;
		public readonly Button Button_Skip;
		public readonly Button Button_Log;
		public readonly Button Button_Sound;
		public readonly VisualElement VisualElement_ClickZone;
		public readonly Label Label_CharacterName;
		public readonly VisualElement Gem_Amber;
		public readonly VisualElement Gem_Cyan;
		public readonly VisualElement Gem_Emerald;
		public readonly Label Label_DialogueText;
		public readonly VisualElement VisualElement_Sigil;
		public readonly VisualElement VisualElement_BacklogModal;
		public readonly Button Button_CloseLog;
		public readonly ScrollView ScrollView_Log;

		public VisualNovelViewBinding(VisualElement parent)
		{
			_____root_____ = parent;
			VisualElement_VignetteFlash = parent.Q<VisualElement>("VisualElement_VignetteFlash");
			Button_Auto = parent.Q<Button>("Button_Auto");
			Button_Skip = parent.Q<Button>("Button_Skip");
			Button_Log = parent.Q<Button>("Button_Log");
			Button_Sound = parent.Q<Button>("Button_Sound");
			VisualElement_ClickZone = parent.Q<VisualElement>("VisualElement_ClickZone");
			Label_CharacterName = parent.Q<Label>("Label_CharacterName");
			Gem_Amber = parent.Q<VisualElement>("Gem_Amber");
			Gem_Cyan = parent.Q<VisualElement>("Gem_Cyan");
			Gem_Emerald = parent.Q<VisualElement>("Gem_Emerald");
			Label_DialogueText = parent.Q<Label>("Label_DialogueText");
			VisualElement_Sigil = parent.Q<VisualElement>("VisualElement_Sigil");
			VisualElement_BacklogModal = parent.Q<VisualElement>("VisualElement_BacklogModal");
			Button_CloseLog = parent.Q<Button>("Button_CloseLog");
			ScrollView_Log = parent.Q<ScrollView>("ScrollView_Log");
		}
	}
}
